# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 23:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('\\d+x\x02{2}')]),
        ),
    ]
